### ISSUE TITLE
Настроить build.gradle и AndroidManifest, добавить необходимые зависимости в проект (~ 1,5 часа)

### ISSUE THREAD

**Issue by SerjePerm** [SerjePerm/FindYourJob#6]
#6
добавить библиотеки
room, retrofit, koin, glide, fragment navigation

задать в манифесте
ориентацию экрана приложения
ссылка на класс Application
разрешение на интернет

**Comment by AlexeyJarlax** [comment]
а эту уже начали?

**Comment by SerjePerm** [comment]
факт. время - 30 мин
